from enum import Enum


class Constants(Enum):
    GRAVITATIONAL_ACCELERATION = 9.81
    SPEED_OF_SOUND = 340.29
    AIR_DENSITY = 1.225
    DRAG_COEFFICIENT_PARALLEL = 0.9
    DRAG_COEFFICIENT_PERPENDICULAR = 2.0
    LIFT_COEFFICIENT_PARALLEL = 0
    LIFT_COEFFICIENT_PERPENDICULAR = 0.75


